name: 'TRM Install'
description: 'Install a package from TRM Registry'
author: 'Simone Gaffurini'
branding:
  icon: 'download'
  color: 'green'
inputs:
  systemDest:
    description: Target system ID
    required: true
  systemAsHost:
    description: Target system application Server
    required: true
  systemSysnr:
    description: Target system instance number
    required: true
  systemClient:
    description: Target system logon client
    required: true
  systemUser:
    description: Target system logon user
    required: true
  systemPassword:
    description: Target system logon password
    required: true
  systemLang:
    description: Target system logon language
    required: true
  packageName:
    description: Package name (on registry)
    required: true
  packageVersion:
    description: Package version (on registry)
    default: latest
    required: false
  registryEndpoint:
    description: Registry endpoint
    default: public
    required: false
  registryAuth:
    description: Registry authentication in JSON format
    required: false
  allowReplace:
    description: Handle conflict during install of an SAP package that already exists on the target system
    default: false
    required: false
  force:
    description: Force install
    default: false
    required: false
  generateTransport:
    description: Generate (if not existent) a workbench transport with all the contents of the package
    default: true
    required: false
  wbTrTargetSystem:
    description: Target system for workbench transport (works if generateTransport is set to true)
    required: false
  transportLayer:
    description: SAP Package transport layer (defaults to system default)
    required: false
  keepOriginalDevclass:
    description: Keep the original SAP package names (no replacement)
    default: true
    required: false
  packageReplacements:
    description: SAP package names replacements in JSON format (works if keepOriginalDevclass is set to false)
    required: false
  importTimeout:
    description: Transport request release timeout, in seconds (increase for larger packages)
    default: 180
    required: false
  ignoreDependencies:
    description: Ignore install/check of package dependencies
    default: false
    required: false
  skipSapEntriesCheck:
    description: Skip required SAP Entries check
    default: false
    required: false
  skipCustImport:
    description: Skip package customizing transport import
    default: false
    required: false
  skipLangImport:
    description: Skip package language transport import
    default: false
    required: false
  skipObjectTypesCheck:
    description: Skip package object types check
    default: false
    required: false
  r3transTempFolder:
    description: Directory for R3Trans temporary files
    required: false
  simpleLog:
    description: Don't use Github Actions annotations on important log messages
    default: false
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'