name: 'TRM Install'
description: 'Install a package from TRM Registry'
author: 'Simone Gaffurini'
branding:
  icon: 'download'
  color: 'green'
inputs:
  systemRFCDest:
    description: Source system RFC connection system ID (SID).
    required: false
  systemRFCAsHost:
    description: Source system RFC connection application server.
    required: false
  systemRFCSysnr:
    description: Source system RFC connection instance number.
    required: false
  systemRFCSAPRouter:
    description: Source system RFC connection SAP router string.
    required: false
  systemRESTEndpoint:
    description: Source system REST connection endpoint.
    required: false
  systemRESTRfcDestination:
    description: Source system REST connection RFC destination.
    required: false
  systemLoginClient:
    description: Source system login client.
    required: false
  systemLoginUser:
    description: Source system login user.
    required: true
  systemLoginPassword:
    description: Source system login password.
    required: true
  systemLoginLanguage:
    description: Source system login language.
    required: true
  r3transDirPath:
    description: Path to R3trans folder.
    required: false
  name:
    description: Name of the TRM package to install.
    required: true
  registryEndpoint:
    description: Endpoint of the publish registry.
    required: false
    default: public
  registryToken:
    description: Authentication token for the registry.
    required: false
  registryAuth:
    description: Authentication object for the registry in JSON format. WIll overwrite authentication token if both are provided.
    required: false
  version:
    description: Version of the TRM package to install.
    required: false
    default: latest
  overwrite:
    description: Update if already installed.
    required: false
    default: true
  integrity:
    description: TRM package integrity.
    required: false
  safe:
    description: Install TRM package in safe mode.
    required: false
    default: false
  noDependencies:
    description: Skip install of TRM package dependencies.
    required: false
    default: false
  noSapEntries:
    description: Skip check of required SAP objects.
    required: false
    default: false
  noObjectTypesCheck:
    description: Skip check of all object types supported.
    required: false
    default: false
  importTransportTimeout:
    description: Transport import timeout (in seconds).
    required: false
    default: 180
  noLanguageTransport:
    description: Skip import of language transport (translations).
    required: false
    default: false
  noCustomizingTransport:
    description: Skip import of customizing transport.
    required: false
    default: false
  keepOriginalAbapPackages:
    description: Keep original ABAP package names.
    required: false
    default: true
  packageReplacements:
    description: Mapping of original ABAP package names to target ABAP package names in JSON format. Has no effect with keepOriginalAbapPackages = true.
    required: false
  transportLayer:
    description: Transport layer for ABAP packages (defaults to system default).
    required: false
  createInstallTransport:
    description: Create an install transport for the package.
    required: false
    default: true
  installTransportTargetSystem:
    description: Target system for the install transport. Has no affect with createInstallTransport = false.
    required: false
  
  
  private:
    description: Visibility of the TRM package to publish
    required: false
    default: false
  abapPackage:
    description: Name of the ABAP package to publish.
    required: false
  shortDescription:
    description: TRM package short description (defaults to the description of the repository running the action).
    required: false
  backwardsCompatible:
    description: Flag that indicates if the current release is backwards compatible with the previous release.
    required: false
    default: true
  keepLatestReleaseManifestValues:
    description: Copy the same manifest values from the latest release
    required: false
    default: false
  authors:
    description: TRM package authors (separated by comma - defaults to the authors in the repository running the action).
    required: false
  keywords:
    description: TRM package keywords (separated by comma - defaults to the keywords in the repository running the action).
    required: false
  git:
    description: TRM package git repository URL (defaults to the repository running the action).
    required: false
  website:
    description: TRM package project website URL (defaults to the website in the repository running the action).
    required: false
  license:
    description: TRM package license (defaults to the license in the repository running the action).
    required: false
  dependencies:
    description: Manually added TRM package dependencies in JSON format.
    required: false
  sapEntries:
    description: Manually added TRM SAP object dependencies in JSON format.
    required: false
  readme:
    description: Path to the file or markup text of the TRM package readme (defaults to repository README.md file content in root, if exists).
    required: false
  releaseTransportTarget:
    description: Transport target used during publish release.
    required: true
  noDependencyDetection:
    description: Skip automatic SAP objects/TRM packages detection.
    required: false
    default: false
  customizingTransports:
    description: Customizing transport to publish (separated by comma).
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'